
#register user
POST http://localhost:8082/api/v1/auth/register
Content-Type: application/json

{
  "firstName": "nicat",
  "lastName": "nicat",
  "email": "nicat@example.com",
  "password": "Nicat2004.",
  "birthDate":"29/12/2004"
}

###
#login user
POST http://localhost:8082/api/v1/auth/login
Content-Type: application/json

{
  "email": "nicat@example.com",
  "password": "Nicat2004."
}

###
# refresh token
POST http://localhost:8082/api/v1/auth/refresh
Content-Type: application/json

{
"userEmail": "nicat@example.com",
"refreshToken": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuaWNhdEBleGFtcGxlLmNvbSIsImlhdCI6MTc1ODcxMzIyMSwiZXhwIjoxNzU4NzE1MDIxfQ.4eLlEfLf_2QbRjxvyq4n1m25ZLCRfZFqJOaFZsr04h8"
}

###
#getUserById
GET http://localhost:8083/api/v1/users/1

