
#register user
POST http://localhost:8082/api/v1/auth/register
Content-Type: application/json

{
  "firstName": "nicat",
  "lastName": "nicat",
  "email": "nicat@example.com",
  "password": "Nicat2004.",
  "birthDate":"29/12/2004"
}

###
#login user
POST http://localhost:8082/api/v1/auth/login
Content-Type: application/json

{
  "email": "nica@example.com",
  "password": "Nicat2004."
}

###
#getUserById
GET http://localhost:8083/api/v1/users/1

